In [1]:
import jax
import jax.numpy as jnp

In [6]:
key = jax.random.PRNGKey(1234)

Array(1, dtype=int32)

In [19]:
key, key_cat = jax.random.split(key, 2)
logits = jnp.array([0.0, 2.0, 1.0, 1.0])
jnp.unique(jax.random.categorical(key_cat, jnp.log(logits), shape=(10000,)), return_counts=True)

(Array([1, 2, 3], dtype=int32), Array([5002, 2482, 2516], dtype=int32))

In [21]:
jnp.unique(jax.random.categorical(key_cat, jnp.log(logits), shape=(10000,)), return_counts=True)

(Array([1, 2, 3], dtype=int32), Array([5002, 2482, 2516], dtype=int32))

In [28]:
jnp.tile(jnp.arange(5), (2, 1))

Array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32)